---
volumes:
  vol_downloads:
    driver: local
    driver_opts:
      type: none
      device: /mnt/download
      o: bind
  vol_media:
    driver: local
    driver_opts:
      type: none
      device: /mnt/media
      o: bind
  vol_sonarr:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/sonarr/run
      o: bind
  vol_sonarr_hevc:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/sonarr_hevc/run
      o: bind
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_sonarr:/config
      - vol_media:/media
      - vol_downloads:/downloads
    ports:
      - 8989:8989
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  sonarr_hevc:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_sonarr:/config
      - vol_media:/media
      - vol_downloads:/downloads
    ports:
      - 8990:8989
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true