---
version: "3"
volumes:
  vol_ombi:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/ombi/run
      o: bind
services:
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_ombi:/config
    ports:
      - 3579:3579
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
