version: '3.8'

services:
  my_app:
    image: nvidia/cuda:12.2.0-base-ubuntu22.04  # Replace with your desired image
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1  # Change to the number of GPUs you want to allocate
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Change "all" to a specific GPU ID if needed
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
