---
volumes:
  vol_downloads:
    driver: local
    driver_opts:
      type: none
      device: /mnt/download
      o: bind
  vol_media:
    driver: local
    driver_opts:
      type: none
      device: /mnt/media
      o: bind
  vol_sabnzbd:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/sabnzbd/run/
      o: bind
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: always    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - vol_sabnzbd:/config
      - vol_downloads:/downloads
    ports:
      - 8080:8080
    labels:
      - com.centurylinklabs.watchtower.enable=true
