# WARNING: Replace the example passwords with secure secrets.
# WARNING: 'my_secret_phpipam_pass' and 'my_secret_mysql_root_pass'

version: '3'
volumes:
  phpipam-db-data:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/phpipam/run/phpipam-db-data
      o: bind
  phpipam-logo:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/phpipam/run/phpipam-logo
      o: bind
  phpipam-ca:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/phpipam/run/phpipam-ca
      o: bind
services:
  phpipam-web:
    image: phpipam/phpipam-www:latest
    ports:
      - "80:80"
    environment:
      - TZ=Europe/London
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=my_secret_phpipam_pass
      - IPAM_DATABASE_WEBHOST=%
    restart: unless-stopped
    volumes:
      - phpipam-logo:/phpipam/css/images/logo
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb
    labels:
      - com.centurylinklabs.watchtower.enable=true
  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    environment:
      - TZ=Europe/London
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=my_secret_phpipam_pass
      - SCAN_INTERVAL=1h
    restart: unless-stopped
    volumes:
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb
    labels:
      - com.centurylinklabs.watchtower.enable=true
  phpipam-mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my_secret_mysql_root_pass
    restart: unless-stopped
    volumes:
      - phpipam-db-data:/var/lib/mysql
    labels:
      - com.centurylinklabs.watchtower.enable=true
