---
- name: make extra foldars
  hosts: localhost
  become: yes

  vars:
    target_folders:
      - /opt/docker/adguard/run/conf
      - /opt/docker/adguard/run/work
  tasks:
    - name: Create folders
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items: "{{ target_folders }}"
