---
volumes:
  vol_notifiarr:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/notifiarr/run
      o: bind
  vol_notifiarr_tmp:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/notifiarr/temp
      o: bind
services:
  notifiarr:
    container_name: notifiarr
    hostname: notifiarr
    image: golift/notifiarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    restart: always
    ports:
      - 5454:5454
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/machine-id:/etc/machine-id
      - vol_notifiarr:/config
      - vol_notifiarr_tmp:/var/run/utmp
    labels:
      - com.centurylinklabs.watchtower.enable=true
